### PR TITLE
Fix Installed Config DIR

### LINKED ISSUE #68: ISAACConfig.cmake: ISAAC_DIR
The location of CMake's [`ISAAC_DIR`](https://github.com/ComputationalRadiationPhysics/isaac/blob/b0aedd368a6c42612668fae5d5d49f3e907db5d1/lib/ISAACConfig.cmake#L22-L23) is currently badly placed.

If for example only the `CMAKE_PREFIX_PATH` is set as a hint, this script sets to the `ISAAC_DIR` to the place of the `*Config.cmake` file itself (`<prefix>/lib/CMake/ISAAC/`) instead of the install root `<prefix>/`. This causes all dependent vars, e.g. include paths, to be wrong.

I would recommend to move the `*Config.cmake` files even in the repo to `lib/cmake/ISAAC/` and fix the path it sets.

Affects the latest release, 1.3.1-1.3.3

### PR DESCRIPTION
**Pull request by ax3l**
Replace the base directory of ISAAC with the prefix on install.

Before, the location of the (nested) CMake config package was taken, which resulted in broken include paths (`<isaac.hpp>` can not be found).

Proposed quick-fix to close #68.

In general, the logic from `ISAACConfig.cmake` needs to go into `CMakeLists.txt` so that it can be included via `add_subdirectories` (in-source mode) and `CMakeLists.txt` should define a namespace `ISAAC::` and an `INTERFACE` target for ISAAC. `ISAACConfig.cmake` then only includes files that are auto-generated by `CMakeLists.txt` (installed mode).

*Note:* in good tradition, this fix has not been tested yet.
*Update:* tested with example/ a little.

### CODE REVIEW

**Comment by ax3l** [comment]
@theZiz with the other fixes in `dev` we could make this a `1.4.0` release when finished.

**Comment by theZiz** [comment]
lgtm, thanks, we should test the most recent dev version with the most recent PIConGPU version. If this works, i guess we can release `1.4.0`

**Comment by ax3l** [comment]
@theZiz can you test and release pls? :-)

**Comment by theZiz** [comment]
Everything is tested and merged execept for the breaking alpaka `Stream`→ `Queue` thingy (will do this when PIConGPU gets an alpaka update). I will release 1.4 now.

**Comment by ax3l** [comment]
Just as a note: PIConGPU is currently at Alpaka 0.3.1 for the next release. The queue thing is in alpaka-dev, right?

**Comment by theZiz** [comment]
I just checked, alpaka 0.3.1 is still using streams, yes. :wink:

**Comment by theZiz** [comment]
kk, done.

**Pull request merged**
