### PR TITLE
Major rework of isaac

### PR DESCRIPTION
**Pull request by FelixTUD**
### **Major rework of isaac**
- standardize naming
- utility functions for rendering added
- split up the render kernel in multiple cleaner kernels
- volume rendering and iso surfaces can now be viewed simultaneously
- the iso surface theshold is now adjustable in the html client
- iso surfaces now also support SSAO
- all the shading is done in a seperate pass, allows debug views in client
- ISAAC_VECTOR_ELEMENT functionality removed for cleaner code

### CODE REVIEW

**Comment by bussmann** [comment]
Awesome!

**Comment by bussmann** [comment]
Question: Would VXAO be possible using supercells or even cells as voxels?

**Comment by FelixTUD** [comment]
Short answer: yes and even a voxel global illumination approach should be possible.

Long answer: it is a bit more complicated than that, a few things to keep in mind:

- Additional 3D buffer for occlusion data and/or GI data is needed
- All voxels in a defined area around the view frustum must be early evaluated, even if they don't contribute to the final image
- Particles and Volume sources can use different grid sizes
- In the render kernel the occlusion amount could be determined by individual rays (can be very demanding as many rays are needed) or the more approximate approuch with cones (however, here we need a mip map hierarchy for the occlusion/GI texture, which is a challenge since alpaka does not support texture memory as of now, and it needs to be updateded at least every few frames to minimize the error)

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
Note for follow-up PRs: Please try to avoid waiting so long before you open a PR. Your PR is mixing nameing changes, refactoring, and new features.
Why do I say this: 
- Naming changes can be revied very easily because you mostly use substitution function in your IDE or sed. During the review I now for renamings that the program flow is not changed. 

For this PR I can not follow all changes because it is far from reviewable.

**Pull request merged**
